language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy3"
# command to install dependencies
install:
  - CRYPTOGRAPHY_ALLOW_OPENSSL_102=1 pip install .
# command to run tests
script:
  #  - nosetests --with-coverage --cover-package=haystackapi --where=tests
  - make test
after_success:
  - coveralls
