version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CarbonAPI"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bxi1tc1eibko"
s3_prefix = "CarbonAPI"
region = "eu-west-3"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"

