version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HaystackAPI"
s3_bucket = "alpha-dev-sam-cli"
s3_prefix = "HaystackAPI"
region = "eu-west-3"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "NOCOMPRESS=\"True\""

