AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A partial implementation of Haystack protocol

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.7
    Timeout: 30
    Environment:
      Variables:
        LOGLEVEL: DEBUG
        DEBUGGING: false
        NOCOMPRESS: true
        PROVIDER: providers.ping.PingProvider
        # PROVIDER: provider.url.URLProvider
        HAYSTACK_URL: s3://cdh-poc1c3ntinel-325540/grid.json
        # HAYSTACK_URL: https://project-haystack.dev/download/defs.json
    Layers:
      - !Ref BaseLayer
      - !Ref HSZincLayer

Resources:
  BaseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/base
      CompatibleRuntimes:
        - python3.7
        - python3.8
      Description: Custom Haystack Zinc libraries
      LayerName: base
      LicenseInfo: BSD 2
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.7

  # Because the snappy module never import the libsnappy.so.1,
  # I must create a Makefile to build this layer
  ParquetLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: .
      CompatibleRuntimes:
        - python3.7
        - python3.8
      Description: Parquet loader layers
      LayerName: parquet
      LicenseInfo: BSD 2
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile

  HSZincLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: .
      CompatibleRuntimes:
        - python3.7
        - python3.8
      Description: Custom Haystack Zinc libraries
      LayerName: HSZinc
      LicenseInfo: BSD 2
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile

  About:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: haystackapi_lambda.about
      Description: Implement the Haystack `About` api
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Environment:
        Variables:
          LOGLEVEL: WARNING
          DEBUGGING: false
          NOCOMPRESS: true
      Tracing: Active
      Events:
        HaystackAboutGET:
          Type: Api
          Properties:
            Path: /about
            Method: get
        HaystackAboutPOST:
          Type: Api
          Properties:
            Path: /about
            Method: post

  Ops:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: haystackapi_lambda.ops
      Description: Implement the Haystack `Ops` api
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Events:
        HaystackAboutGET:
          Type: Api
          Properties:
            Path: /ops
            Method: get
        HaystackAboutPOST:
          Type: Api
          Properties:
            Path: /ops
            Method: post

  Formats:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: haystackapi_lambda.formats
      Description: Implement the Haystack `Formats` api
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Events:
        HaystackAboutGET:
          Type: Api
          Properties:
            Path: /formats
            Method: get
        HaystackAboutPOST:
          Type: Api
          Properties:
            Path: /formats
            Method: post

  Read:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: haystackapi_lambda.read
      Description: Implement the Haystack `read` api
      Role: arn:aws:iam::695980681400:role/cdh_poc1paris_59238
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Events:
        HaystackAboutPOST:
          Type: Api
          Properties:
            Path: /read
            Method: post

  Nav:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: haystackapi_lambda.nav
      Description: Implement the Haystack `nav` api
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Events:
        HaystackAboutGET:
          Type: Api
          Properties:
            Path: /nav
            Method: get
        HaystackAboutPOST:
          Type: Api
          Properties:
            Path: /nav
            Method: post

  WatchSub:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: haystackapi_lambda.watchSub
      Description: Implement the Haystack `watchSub` api
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Events:
        HaystackAboutGET:
          Type: Api
          Properties:
            Path: /watchSub
            Method: get
        HaystackAboutPOST:
          Type: Api
          Properties:
            Path: /watchSub
            Method: post

  WatchUnsub:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: haystackapi_lambda.watchUnsub
      Description: Implement the Haystack `watchUnsub` api
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Events:
        HaystackAboutGET:
          Type: Api
          Properties:
            Path: /watchUnsub
            Method: get
        HaystackAboutPOST:
          Type: Api
          Properties:
            Path: /watchUnsub
            Method: post

  WatchPoll:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: haystackapi_lambda.watchPoll
      Description: Implement the Haystack `watchPoll` api
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Events:
        HaystackAboutGET:
          Type: Api
          Properties:
            Path: /watchPoll
            Method: get
        HaystackAboutPOST:
          Type: Api
          Properties:
            Path: /watchPoll
            Method: post

  PointWrite:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: haystackapi_lambda.pointWrite
      Description: Implement the Haystack `pointWrite` api
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Events:
        HaystackAboutGET:
          Type: Api
          Properties:
            Path: /pointWrite
            Method: get
        HaystackAboutPOST:
          Type: Api
          Properties:
            Path: /pointWrite
            Method: post

  HisRead:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: haystackapi_lambda.hisRead
      Description: Implement the Haystack `hisRead` api
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Layers:
        - !Ref ParquetLayer
      Events:
        HaystackAboutGET:
          Type: Api
          Properties:
            Path: /hisRead
            Method: get
        HaystackAboutPOST:
          Type: Api
          Properties:
            Path: /hisRead
            Method: post

  HisWrite:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: haystackapi_lambda.hisWrite
      Description: Implement the Haystack `hisWrite` api
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Layers:
        - !Ref ParquetLayer
      Events:
        HaystackAboutGET:
          Type: Api
          Properties:
            Path: /hisWrite
            Method: get
        HaystackAboutPOST:
          Type: Api
          Properties:
            Path: /hisWrite
            Method: post

  InvokeAction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: haystackapi_lambda.invokeAction
      Description: Implement the Haystack `invokeAction` api
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Events:
        HaystackAboutGET:
          Type: Api
          Properties:
            Path: /invokeAction
            Method: get
        HaystackAboutPOST:
          Type: Api
          Properties:
            Path: /invokeAction
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AboutAPI:
    Description: "Haystack `about` API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/src/about"
  AboutFunction:
    Description: "Haystack `about` API"
    Value: !GetAtt About.Arn

  OpsAPI:
    Description: "Haystack `ops` API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/src/ops"
  OpsFunction:
    Description: "Haystack `ops` API"
    Value: !GetAtt Ops.Arn

  FormatsAPI:
    Description: "Haystack `formats` API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/src/formats"
  FormatsFunction:
    Description: "Haystack `formats` API"
    Value: !GetAtt Formats.Arn

  HisWrite:
    Description: "Haystack `hisWrite` API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/src/hisWrite"
  HisWriteFunction:
    Description: "Haystack `hisWrite` API"
    Value: !GetAtt HisWrite.Arn

  InvokeAction:
    Description: "Haystack `invokeAction` API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/src/invokeAction"
  InvokeActionFunction:
    Description: "Haystack `invokeAction` API"
    Value: !GetAtt InvokeAction.Arn

  NavAction:
    Description: "Haystack `nav` API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/src/nav"
  NavFunction:
    Description: "Haystack `nav` API"
    Value: !GetAtt Nav.Arn

  PointWriteAction:
    Description: "Haystack `pointWrite` API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/src/pointWrite"
  PointWriteFunction:
    Description: "Haystack `pointWrite` API"
    Value: !GetAtt Ops.Arn

  ReadAction:
    Description: "Haystack `read` API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/src/read"
  ReadFunction:
    Description: "Haystack `read` API"
    Value: !GetAtt Read.Arn

  WatchPollAction:
    Description: "Haystack `watchPoll` API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/src/watchPoll"
  WatchPollFunction:
    Description: "Haystack `watchPoll` API"
    Value: !GetAtt WatchPoll.Arn

  WatchSubAction:
    Description: "Haystack `watchSub` API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/src/watchSub"
  WatchSubFunction:
    Description: "Haystack `watchSub` API"
    Value: !GetAtt WatchSub.Arn

  WatchUnsubAction:
    Description: "Haystack `watchUnsub` API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/src/watchUnsub"
  WatchUnsubFunction:
    Description: "Haystack `watchUnsub` API"
    Value: !GetAtt WatchUnsub.Arn
